version: '3.4'

services:
  javascripttuturialfile:
    image: javascripttuturialfile
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m python3 "]
    ports:
      - 5678:5678
